name: medicapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pinput: ^2.2.12
  intl_phone_field: ^3.2.0
  flutter_map: ^6.1.0
  location: ^5.0.0
  flutter_spinkit: ^5.2.0
  http: ^1.2.0
  flutter_map_location_marker: ^8.0.8
  lottie: ^3.1.0
  introduction_screen: ^2.1.0
  flutter_svg: ^2.0.10+1
  intro_screen_onboarding_flutter: ^1.0.0
  carousel_slider: ^4.2.1
  curved_navigation_bar: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo.ttf
    - family: Dancing Script
      fonts:
        - asset: fonts/Danc.ttf
    - family: Caveat
      fonts:
        - asset: fonts/Caveat.ttf
    - family: Darine-Regular
      fonts:
        - asset: fonts/Darine.ttf
